### ISSUE TITLE
Can't reproduce the accuracy 84.42%

### ISSUE THREAD

**Issue by zyh-uaiaaaa** [hangyu94/Ada-CM#16]
Hi,

I run the provided code with 4000 labels on RAF-DB and only get accuracy of 79%. Can you provide the  training log and the saved 84.42% model using the provided code for me to find the reason? Thanks very much.

**Comment by hangyu94** [comment]
If can, please attach a paragraph of your output.

**Comment by zyh-uaiaaaa** [comment]
<img width="1053" alt="截屏2023-04-10 上午11 57 29" src="https://user-images.githubusercontent.com/52573512/230810537-17780c5b-74be-4151-919b-d0fa03800756.png">
<img width="1156" alt="截屏2023-04-10 上午11 57 39" src="https://user-images.githubusercontent.com/52573512/230810566-72acab09-924c-486d-a805-dd61e41dc63e.png">

**Comment by zyh-uaiaaaa** [comment]
Thanks for your help. Can you help me identify where is the problem?

**Comment by hangyu94** [comment]
The problem may come from the labeled data. From your results, there is only 15 iters during the 'Train Stats'. However, when the number of labeled data is 4,000, the iteration here should be 4000/16=250.

**Comment by zyh-uaiaaaa** [comment]
The iters number of 15 is because I set the batch size as 256 instead of 16. Should batch size number has such great effect on the performance?

**Comment by hangyu94** [comment]
Sorry, I do not run this code with the large batch size, e.g., 256. However, I just ran the code again and the results is no problem. It is suggested to run it with the default setting.

**Comment by zyh-uaiaaaa** [comment]
Thanks, I will try the small batch size first. If I have any other question, can I reach you through Wechat. My Wechat number is zhangyuhang200004, I have published several papers on FER and I really want to discuss with other researchers. Thank you very much!!!!
